### PR TITLE
Fixed a bug with wrong rows being edited in reference author fields

### LINKED ISSUE #392: Reference: Known bugs
#233 related

Check discord/reference

### PR DESCRIPTION
**Pull request by kaarleol**
closes #392

### CODE REVIEW

**Comment by kaarleol** [comment]
Using this same branch for more tasks since the bug fixes are pretty central and I don't want to mess with merging
closes #265 
closes #394

File: frontend/src/components/DetailView/common/EditableTable.tsx [hunk 1]
```diff
@@ -21,37 +21,53 @@ const getNewState = (state: RowState): RowState => {
...
-    // TODO: Using static index - need to use some id, sorting breaks this
-    const rowClicked = (index: number | undefined) => {
+    // uses either 'row.original.index' or 'staticRowIndex' based on 'useDefinedIndex'
+    const rowClicked = () => {
+      let index = useDefinedIndex ? row.original.index : staticRowIndex
       if (index === undefined) return
-      const items = [...editData[field]]
+      let items: Array<EditDataType<T>>
+      if (useObject) {
+        items = [editData[field]]
```
Comment (iritmaximus) [inline frontend/src/components/DetailView/common/EditableTable.tsx:58]: Is `editData[field]` quaranteed to exist so that no index/field out of range error occurs?

File: frontend/src/components/DetailView/common/EditableTable.tsx [hunk 2]
```diff
@@ -21,37 +21,53 @@ const getNewState = (state: RowState): RowState => {
...
+        index = 0
+      } else {
+        items = [...editData[field]]
+      }
+
       if (items[index].rowState === 'new') {
         items.splice(index, 1)
-        setEditData({ ...editData, [field]: items })
+        setEditData({ ...editData, [field]: useObject ? items[0] : items })
```
Comment (iritmaximus) [inline frontend/src/components/DetailView/common/EditableTable.tsx:66]: This relates also to the `editData[field]` but is also items quaranteed to have at least one element?

**Review by iritmaximus — CHANGES_REQUESTED** [review]
Otherwise this is mergeable.

File: frontend/src/components/DetailView/common/EditableTable.tsx (hunk 1 above)
Comment (kaarleol) [reply frontend/src/components/DetailView/common/EditableTable.tsx:58]: field: keyof EditDataType<ParentType>

'field' is typed to be a key of editData, so you shouldn't be able to push code to main where editData[field] isn't defined. Is this sufficient or should I write a hard check in the code for it?

File: frontend/src/components/DetailView/common/EditableTable.tsx (hunk 2 above)
Comment (kaarleol) [reply frontend/src/components/DetailView/common/EditableTable.tsx:66]: const ActionRow is only called when a row in the table is clicked. Which in theory should mean that there is at least a single element in items. But again not sure if this is sufficient

File: frontend/src/components/DetailView/common/EditableTable.tsx (hunk 1 above)
Comment (iritmaximus) [reply frontend/src/components/DetailView/common/EditableTable.tsx:58]: Ah that is fair.

File: frontend/src/components/DetailView/common/EditableTable.tsx (hunk 2 above)
Comment (iritmaximus) [reply frontend/src/components/DetailView/common/EditableTable.tsx:66]: Yeah this is reasonable. It would probably get caught in the `if (index === undefined) return` clause.

**Review by iritmaximus — APPROVED** [review]
LGTM
